-- Baseline schema for wallet-service (matches Wallet, WalletTransaction, WalletHold entities).
CREATE TABLE wallets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL UNIQUE,
    currency          VARCHAR(3)  NOT NULL,
    balance           BIGINT      NOT NULL DEFAULT 0,
    available_balance BIGINT      NOT NULL DEFAULT 0,
    updated_at        TIMESTAMP   NOT NULL
);

CREATE TABLE wallet_transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id   BIGINT       NOT NULL,
    type        VARCHAR(255) NOT NULL,
    amount      BIGINT       NOT NULL,
    status      VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP    NOT NULL
);
CREATE INDEX idx_wallet_tx_wallet_id ON wallet_transactions (wallet_id);

CREATE TABLE wallet_holds (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id      BIGINT       NOT NULL REFERENCES wallets (id),
    hold_reference VARCHAR(255) NOT NULL UNIQUE,
    amount         BIGINT       NOT NULL,
    status         VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP,
    expires_at     TIMESTAMP
);
CREATE INDEX idx_wallet_holds_status_expires ON wallet_holds (status, expires_at);
