-- Baseline schema for notification-service (matches the Notification entity).
CREATE TABLE notifications (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    message VARCHAR(255),
    sent_at TIMESTAMP
);
CREATE INDEX idx_notifications_user ON notifications (user_id);
