-- Baseline schema for transaction-service (matches the Transaction entity).
CREATE TABLE "transaction" (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id   BIGINT           NOT NULL,
    receiver_id BIGINT           NOT NULL,
    amount      DOUBLE PRECISION NOT NULL,
    "timestamp" TIMESTAMP        NOT NULL,
    status      VARCHAR(255)     NOT NULL
);
CREATE INDEX idx_transaction_sender ON "transaction" (sender_id);
CREATE INDEX idx_transaction_receiver ON "transaction" (receiver_id);
