-- Baseline schema for reward-service (matches the Reward entity).
CREATE TABLE rewards (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    points         DOUBLE PRECISION,
    sent_at        TIMESTAMP,
    transaction_id BIGINT UNIQUE
);
CREATE INDEX idx_rewards_user ON rewards (user_id);
