-- Baseline schema for user-service (matches the User entity).
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) UNIQUE,
    password   VARCHAR(255),
    role       VARCHAR(255)
);
